eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/api/v1/orders
  payment-service:    
    endpoints:  
      endpoint:
        uri: http://payment-service/api/v1/payment/doPayment-updated

