server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVER
  cloud:
    config:
      import-check.enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
