server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: ${CONNECTION_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  config:
    import: optional:configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#Circuitbreaker configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
  health:
    circuitbreakers:
      enabled: true


#Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      orderPaymentCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      orderPaymentRetry:
        max-attempts: 3
        wait-duration: 5s

